name: Manual Playwright Test and Report

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Generate HTML report
        run: |
          npx playwright show-report > report.html
          mkdir -p reports
          mv report.html reports/

      - name: Upload Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: reports/